# Generated by Django 3.1 on 2020-09-09 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='社員番号')),
                ('lastName', models.CharField(max_length=20, verbose_name='氏（漢字）')),
                ('firstName', models.CharField(max_length=20, verbose_name='名（漢字）')),
                ('lastKanaName', models.CharField(max_length=20, verbose_name='氏（かな）')),
                ('firstKanaName', models.CharField(max_length=20, verbose_name='名（かな）')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=100, verbose_name='eメールアドレス')),
                ('password', models.CharField(max_length=20, verbose_name='パスワード')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('gender', models.BooleanField(verbose_name='性別')),
                ('section', models.CharField(choices=[('役員', '役員'), ('イノベーション推進室', 'イノベーション推進室'), ('市場開発部', '市場開発部'), ('経営管理本部', '経営管理本部'), ('公共事業本部', '公共事業本部'), ('システム開発事業部', 'システム開発事業部')], max_length=20, verbose_name='部署')),
                ('jikoShokai', models.TextField(max_length=255, verbose_name='自己紹介')),
            ],
        ),
    ]
