# Generated by Django 3.1 on 2020-09-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200926_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('未選択', '未選択'), ('男性', '男性'), ('女性', '女性')], default='未選択', max_length=10, verbose_name='性別'),
        ),
    ]
